### ISSUE TITLE
请求将 collecotr.github.com:443 移除隐私保护

### ISSUE THREAD

**Issue by Cillo-x** [Mythologyli/ZJU-Rule#37]
原因是会导致Scoop 连不上Github 上的官方仓库
![image](https://github.com/Mythologyli/ZJU-Rule/assets/58360548/d4ca499e-a316-4b5a-b396-c1c67b9c8378)
我查 clash 的 log 发现拦截了好多的请求
![image](https://github.com/Mythologyli/ZJU-Rule/assets/58360548/db0e54d0-a40e-46c6-8aca-8116d0c13188)
手动在配置文件中把这一条删除了就正常了
![image](https://github.com/Mythologyli/ZJU-Rule/assets/58360548/f8659d99-3b65-4183-a8dd-a5d0cdd465b5)

**Comment by Cillo-x** [comment]
虽然不知道 collecotr.github.com 是Github 拿来干什么用的

**Comment by Mythologyli** [comment]
你可以先通过 Clash for Windows 的 Parsers 功能缓解此问题
进入 Profiles，找到对应订阅，右键，Parsers - Edit Parsers
填写以下内容：
```
parsers:
  - url: https://sub.zjurule.xyz/xxxxxx
    yaml:
      prepend-rules:
        - DOMAIN-SUFFIX,collecotr.github.com,🚀 节点选择
```
关于 collecotr.github.com 的具体作用尚不明确，先保留原有配置，此 issue 保留
